# Sample config

[main]
vardir = /var/opt/puppetlabs/puppet/cache

[agent]
server = openvox  # Change to your OpenVox server
ca_server = $server # Change if your OpenVox CA server is different than your OpenVox server
