---
- name: Configure System
  hosts: localhost
  become: true
  vars:
    VAULT_ADDR: "{{ lookup('ansible.builtin.env', 'VAULT_ADDR') }}"
    VAULT_ENGINGE_MOUNT_POINT: "{{ lookup('ansible.builtin.env', 'VAULT_ENGINGE_MOUNT_POINT') }}"
  tasks:
  - name: Authenticate with Vault and get token
    community.hashi_vault.vault_login:
      url: "{{ VAULT_ADDR }}"
      auth_method: "approle"
      role_id: "{{ lookup('file', '/etc/vault/role_id') | trim }}"
      secret_id: "{{ lookup('file', '/etc/vault/secret_id') | trim }}"
    register: vault_auth

  - name: Read Common Information
    community.hashi_vault.vault_kv2_get:
      url: "{{ VAULT_ADDR }}"
      auth_method: token
      token: "{{ vault_auth.login.auth.client_token }}"
      engine_mount_point: "{{ VAULT_ENGINGE_MOUNT_POINT }}"
      path: "immutable-os/common"
    register: common_info

  - name: Include tasks from tasks directory
    ansible.builtin.include_tasks: "{{ item }}"
    with_fileglob:
      - "{{ tasks_dir }}/*.yaml"
