name: Build Container

on:
  push:
    branch:
      - main
  
  schedule:
    # Patch Tuesday (Second Tuesday of the month)
    - cron: "0 7 8-14 * 2"

jobs:
  build-container:
    name: Build Container Image
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          fetch-tags: 'true'

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}.{{minor}}.{{patch}}

      - name: Auth with Vault
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
        run: |
          vault write \
            -field=token \
            auth/approle/login \
            role_id=$(cat /home/runner/.vault-role) \
            secret_id=${{ secrets.VAULT_SECRET }} > .vault-token

      - name: Run scripts
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          GLOBAL_ADMINS: ${{ secrets.GLOBAL_ADMINS }}
          GLOBAL_SSH: ${{ secrets.GLOBAL_SSH }}
          MACHINE_ADMINS_FORMAT: ${{ secrets.MACHINE_ADMINS_FORMAT }}
          MACHINE_SSH_FORMAT: ${{ secrets.MACHINE_SSH_FORMAT }}
        run: |
          export VAULT_TOKEN=$(cat .vault-token)
          for script in set_perms update_files
          do
            chmod +x scripts/${script}/${script}.sh
            ./scripts/${script}/${script}.sh
          done

      - name: Buildah Build
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: Containerfile
          tags: ${{ steps.meta.outputs.tags || steps.meta_pr.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels || steps.meta_pr.outputs.labels }}

      - name: Push image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Trigger other builds
        env:
          repo_owner: ${{ github.repository_owner }}
          token: ${{ secrets.TRIGGER_PAT }}
        run: |
          chmod +x scripts/trigger_builds/trigger_builds.sh
          ./scripts/trigger_builds/trigger_builds.sh
